name: Solidity Linter
on:
  pull_request:
    branches: [ main ]
jobs:
  solhint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install Solhint
        run: npm install -g solhint
      - name: Run Solhint
        run: solhint 'contracts/**/*.sol' || true
